version: '3'

services:
  backend:
    build: ./api
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ${BACKEND_PATH_HOST}:/var/www/api
    ports:
      - 9000:9000
    command: npm run start

  frontend:
    build: ./frontend
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ${FRONTEND_PATH_HOST}:/var/www/frontend
    ports:
      - 3000:3000
    command: npm run start

  redis:
    image: "redis:alpine"
