version: '3'

services:
  frontend:
    build: ./frontend
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ./frontend:/var/www/frontend
    ports:
      - 3000:3000
    command: npm run start

  redis:
    image: "redis:alpine"

  backend:
    build: ./api
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ./api:/var/www/api
    ports:
      - 9000:9000
    command: npm run start
