version: '3'

services:
  backend:
    build: ./api
    volumes:
      - ${BACKEND_PATH_HOST}:/var/www/api
    ports:
      - 9000:9000
    command: npm run start

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/var/www/frontend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm run start

  redis:
    image: "redis:alpine"
